server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: 12345
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create #create update none
  logging:
    level:
      org.hibernate.SQL: debug
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest